[versions]
agp = "8.13.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.00"
koog = "0.5.0"
room = "2.8.2"
koin = "4.1.1"
android-appcompat = "1.7.1"
koin-annotations = "2.2.0"
ksp = "2.2.0-2.0.2"

retrofit = "2.11.0"
okhttp = "4.12.0"
gson = "2.10.1"
preference = "1.2.1"
ktorVersion = "2.3.12"
genai = "0.1.2"

[libraries]
androidx-material-icons= { module = "androidx.compose.material:material-icons-extended" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-room-compiler = { module = "androidx.room:room-compiler", name="room-compiler", version.ref = "room" }
koog-agent = { module = "ai.koog:koog-agents",name="koog", version.ref = "koog" }
androidx-room-runtime = { module = "androidx.room:room-runtime", name="room-runtime", version.ref = "room" }

android-appcompat = {module = "androidx.appcompat:appcompat", version.ref = "android-appcompat"}
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-android-test = { module = "io.insert-koin:koin-android-test", version.ref = "koin" }
preference = {module="androidx.preference:preference-ktx",version.ref = "preference"}


retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit_gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp_logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

ktor-client-core ={group ="io.ktor:ktor-client-core", name ="client-core", version.ref = "ktorVersion"}
ktor-client-cio ={group ="io.ktor:ktor-client-cio", name ="client-cio", version.ref = "ktorVersion"}
ktor-client-contentnegotian ={group ="io.ktor:ktor-client-content-negotiation", name ="client-content-negotiation", version.ref = "ktorVersion"}
ktor-logging ={group ="io.ktor:ktor-client-logging", name ="logging", version.ref = "ktorVersion"}
google-genai = { group = "com.google.ai.client.generativeai:generativeai", name = "ai", version.ref = "genai" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktor-serialization-json ={id ="io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion"}
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose = { id = "org.jetbrains.compose", version.ref = "composeBom" }
kotlinserialization = {id = "org.jetbrains.kotlin.plugin.serialization",version.ref  ="kotlin"}


